# -*- coding: utf-8 -*-
"""Hernandez_Ricardo_Homework1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y2fF-dWx7e2-Y-mWe6MrakYzXdW8weaY
"""

#Author: Ricardo Hernandez
#Program: Number Arithmetic

#This block: Prompt user for numbers
print("Please enter a number ")
#Convert user input from str to float
num1 = float(input())
print("Please enter another number ")
#convert user input from str to float
num2 = float(input())

#This block: Complete arithmetic and print value
print("{} - {} = {}".format(num1, num2, (num1 - num2)))
print("{} + {} = {}".format(num1, num2, (num1 + num2)))

#Enhancement: Allow user to choose operation
print("\n")
#Prompt first number
print("Please enter a number")
num1 = float(input())
#Prompt operation
print("\nPlease choose an operation by entering 1-6")
print("1: Addition\n2: Subtraction\n3: Multiplication\n4: Regular Divison\n5: Floor Division\n6: Modulo")
operation = int(input())
#Validate operation
while(operation > 6 or operation < 1):
  print("Please choose a valid operation by selecting a number 1-6")
  operation = int(input())
#Prompt second number
print("\nPlease enter another number")
num2 = float(input())
#Complete arithmetic and print number
#Addition
if(operation == 1):
  print("{} + {} = {}".format(num1, num2, (num1 + num2)))
#Subtraction
elif(operation == 2):
  print("{} - {} = {}".format(num1, num2, (num1 - num2)))
#Multiplication
elif(operation == 3):
  print("{} * {} = {}".format(num1, num2, (num1 * num2)))
#Regular Division
elif(operation == 4):
  if(num2 == 0):
    print("ERROR: Undefined. Division by 0 not allowed!")
  else:
    print("{} / {} = {}".format(num1, num2, (num1/num2)))
#Floor Division
elif(operation == 5):
  if(num2 == 0):
    print("ERROR: Undefined. Division by 0 not allowed!")
  else:
    print("{} // {} = {}".format(num1, num2, (num1//num2)))
#Modulo. Catch all case if user somehow bypasses operator input verification
else:
  if(num2 == 0):
    print("ERROR: Undefined. Modulo by 0 not allowed!")
  else:
    print("{} % {} = {}".format(num1, num2, (num1%num2)))

#Author: Ricardo Hernandez
#Program: Celsius to Fahrenheit & Vice Versa, LB to KG & Vice Versa

POUNDS_PER_KILOGRAM = 2.20462262185
#Used for the continuation of the program
convertAnother = 'Y'

def celsiusToFahrenheit(number):
  print("{} C = {} F".format(number, ((number * (9/5) + 32))))

def fahrenheitToCelsius(number):
  print("{} F = {} C".format(number, ((number - 32) / (9/5))))

def poundsToKilograms(number):
  print ("{} lbs = {} kg".format(number, (number/POUNDS_PER_KILOGRAM)))

def kilogramsToPounds(number):
  print("{} kg = {} lbs".format(number, (number * POUNDS_PER_KILOGRAM)))

#ENHANCEMENT: Allow for multiple conversions in one run
while (convertAnother == 'Y' or convertAnother == 'y'):
  #Prompt for conversion
  print("Choose a conversion by entering a number 1-4")
  print(" 1: Celsius to Fahrenheit")
  print(" 2: Fahrenheit to Celsius")
  #ENHANCEMENT: Allow for conversion from lbs to kg and vice versa
  print(" 3: Pounds to Kilograms")
  print(" 4: Kilograms to Pounds")
  #Validate entry
  conversionChoice = int(input())
  while(conversionChoice < 1 or conversionChoice > 4):
    print("Please choose a valid conversion by entering a number 1-4")
    conversionChoice = int(input())

  #Prompt for number to convert
  print("\nEnter a number to convert")
  numToConvert = float(input())

  #Begin conversions
  #Celsius to Fahrenheit
  if (conversionChoice == 1):
    celsiusToFahrenheit(numToConvert)
  #Fahrenheit to Celsius
  elif (conversionChoice == 2):
    fahrenheitToCelsius(numToConvert)
  #Pounds to Kilograms
  elif(conversionChoice == 3):
    poundsToKilograms(numToConvert)
  #Kilograms to Pounds. Catch all case if user bypasses input verification
  else:
    kilogramsToPounds(numToConvert)
  print("\nWould you like to convert another number? Y/N")
  convertAnother = input()

