# -*- coding: utf-8 -*-
"""HernandezRicardo_Discussion3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goqHeqrb2nDJtp5K0pWgenj4E1fwaxMN
"""

#Ricardo Hernandez

def extendDate(date):
  validDate = True
  leapYear = True
  #Check that the date has the right amount of chars (6/7/8)
  try:
    if len(date) not in [8,9,10]:
      return ("Invalid format. Please enter a date using the following format: mm/dd/yyyy")
  except:
    return("Exception caught. You must enter a date using the following format mm/dd/yyyy")
  #Start by segmenting date into an array
  dateArray = date.split("/")
  #Then add a 0 to the month and/or day if either are one digit
  for i in [0,1]:
    if len(dateArray[i]) == 1:
      dateArray[i] = "0" + dateArray[i]
  #Check for leap year
  if(int(dateArray[2]) % 4 != 0):
    leapYear = False
  #Check that month is valid
  if((int(dateArray[0])) < 1 or (int(dateArray[0])) > 12):
    validDate = False
  #Check that day is non zero, non negative
  if(int(dateArray[1]) < 1):
    validDate = False
  #Only proceed if date is valid so far
  if(validDate == True):
    #Check Jan
    if(dateArray[0] == "01" and int(dateArray[1]) > 31):
      validDate = False
    #Check Mar
    elif(dateArray[0] == "03" and int(dateArray[1]) > 31):
      validDate = False
    #Check Apr
    elif(dateArray[0] == "04" and int(dateArray[1]) > 30):
      validDate = False
    #Check May
    elif(dateArray[0] == "05" and int(dateArray[1]) > 31):
      validDate = False
    #Check Jun
    elif(dateArray[0] == "06" and int(dateArray[1]) > 30):
      validDate = False
    #Check Jul
    elif(dateArray[0] == "07" and int(dateArray[1]) > 31):
      validDate = False
    #Check Aug
    elif(dateArray[0] == "08" and int(dateArray[1]) > 31):
      validDate = False
    #Check Sep
    elif(dateArray[0] == "09" and int(dateArray[1]) > 30):
      validDate = False
    #Check Oct
    elif(dateArray[0] == "10" and int(dateArray[1]) > 31):
      validDate = False
    #Check Nov
    elif(dateArray[0] == "11" and int(dateArray[1]) > 30):
      validDate = False
    #Check Dec
    elif(dateArray[0] == "12" and int(dateArray[1]) > 31):
      validDate = False
    #Check Feb
    if(leapYear == True):
      if(dateArray[0] == "02" and int(dateArray[1]) > 29):
        validDate = False
    else:
      if(dateArray[0] == "02" and int(dateArray[1]) > 28):
        validDate = False
  #Once the program reaches this point, the date should be validated, therefore
  #only proceed if validDate == True
  if validDate == True:
    match(dateArray[0]):
      case "01":
        returnValue = "January"
      case "02":
        returnValue = "February"
      case "03":
        returnValue = "March"
      case "04":
        returnValue = "April"
      case "05":
        returnValue = "May"
      case "06":
        returnValue = "June"
      case "07":
        returnValue = "July"
      case "08":
        returnValue = "August"
      case "09":
        returnValue = "September"
      case "10":
        returnValue = "October"
      case "11":
        returnValue = "November"
      case "12":
        returnValue = "December"

    #Lesson learned: You can strip characters from the beginning of a Python string
    #with the "lstrip" method
    return(returnValue + " {}, {}".format(dateArray[1].lstrip("0"),dateArray[2]))
  else:
    return("Invalid date. Please enter a date using the following format: mm/dd/yyyy")

print("Enter a date using the following format: mm/dd/yyyy")
print(extendDate(input()))